// Mocks generated by Mockito 5.0.13 from annotations
// in flutterlab/test/mock/domain/repository/user/mock.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:flutterlab/data/domain_impl/repository/user/user_list_repository_impl.dart'
    as _i2;
import 'package:flutterlab/domain/entity/user/user_list_entity.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [UserListRepositoryImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserListRepositoryImpl extends _i1.Mock
    implements _i2.UserListRepositoryImpl {
  MockUserListRepositoryImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.UserListEntity>> fetch() => (super.noSuchMethod(
          Invocation.method(#fetch, []),
          returnValue:
              Future<List<_i4.UserListEntity>>.value(<_i4.UserListEntity>[]))
      as _i3.Future<List<_i4.UserListEntity>>);
  @override
  String toString() => super.toString();
}
